print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
print("Utsho Sadhak Joy")
print('O----')
print(' ||||')
print('*'* 10)
